### PR TITLE
CreatedAt Time Expression

### PR DESCRIPTION
**Pull request by florianpreusner**
Related issue: https://github.com/8p/guzzle-wsse-middleware/issues/5

### CODE REVIEW

**Comment by florianpreusner** [comment]
@mathielen Can you review that? Just want to make sure that the implementation fits to your request/idea.

**Comment by mathielen** [comment]
That looks nice! :+1:

**Comment by florianpreusner** [comment]
Alright, thanks for reviewing. I will release a new version later today.

**Comment by mathielen** [comment]
Very cool. Thank you

**Pull request merged**
