### PR TITLE
transform into bundle (concept)

### PR DESCRIPTION
**Pull request by gregurco**
This pull request is a concept, how to make wsse plugin optional in guzzle bundle.

Read more: https://github.com/8p/GuzzleBundle/pull/129

Todo:
---
- [ ] add GuzzleBundle in requirements in composer.json
- [ ] rename GuzzleWsseBundle into EightPointsGuzzleWsseBundle
- [ ] tests
- [ ] travis build

### CODE REVIEW

**Comment by florianpreusner** [comment]
I think we should split that. So the plugin can stay and will be integrated by a new EightPointsGuzzleWsseBundle. Because than the plugin can also be used directly by a plain Guzzle integration. What do you think, @gregurco?

**Comment by p5vgregurco** [comment]
I'm agree with you but I had only one source to do a PR and I did it here :) So I think you can create new repository and I will do PR to new repository. Did I correctly understand you?

**Comment by florianpreusner** [comment]
True. What do you think about creating this repo by your user/organization. It doesn't have to be in @8p. Just an idea. But you put so much time in this features maybe this would be nice for you to have this "hosted" by your own. If not, I can also create a new repo, sure. Just tell me what you prefer 👍

**Comment by gregurco** [comment]
Yep, I can create and maintain it. As soon as I will create it, I will post the link here.
Thank you for this possibility :)

**Comment by gregurco** [comment]
@florianpreusner hello! Yesterday I made a commit in GuzzleBundle. I added interface and made some additional changes. Also I created new repository with plugin and implementation of newly created interface. You can see code there: https://github.com/gregurco/EightPointsGuzzleWssePlugin/tree/init
Do you have any remarks or suggestions? For example about repository name, namespace, implementation or something another?
If all is ok, then I can continue with testing of new implementation, writing phpunit tests and documentation :)
Thanks.

**Comment by florianpreusner** [comment]
Hi @gregurco! Nice!
- [ ] Why not calling it gregurco/guzzle-bundle-wsse-plugin? I think we should make it clear that this is a plugin for a bundle and not a plugin for guzzle itself. The name of the repo should also change of course. But this is just a suggestion.

- [ ] In composer.json some urls are wrong: "https://github.com/gregurco/EightPointsGuzzleWssePlugin/contributors", ...

👍  I like it a lot :)

**Comment by gregurco** [comment]
@florianpreusner thank you, it's good idea :+1: just renamed repository, package name and fixed links. Tomorrow I will start to test and I will write when it will be ready :)

**Comment by gregurco** [comment]
I closed this PR. Let's continue discussion in https://github.com/8p/GuzzleBundle/pull/129

**Pull request closed without merging**
